### ISSUE TITLE
Specify labels at the point of observation?

### ISSUE THREAD

**Issue by jml** [bitnomial/prometheus#1]
I was looking into Prometheus libraries and was attracted to this one by its type safety and restricted use of IO.

However, I can't figure out how to set labels at the point of observation, which is a particularly common use case. e.g. I'd like to record the method & status code of HTTP requests & responses alongside their latency.

This is something of a blocker for me. Are you open to accepting patches?

**Comment by LukeHoersten** [comment]
I'm definitely open to accepting patches! Thanks for the interest. Any feedback on the design is welcome as well.

**Comment by jml** [comment]
Great!

Quick, sketchy thoughts on how we might do this:

- We need to separate the current `Labels` into two different concepts: the label names of a vector (e.g. `method`, `status_code`), and the values for label names for a vector (e.g. `method=GET,status_code=200`). This is probably going to have to break backwards compatibility.
- Probably while doing this should make a new `LabelName` newtype that can be used
- New `Vector` type that wraps any other given metric type and has a set of `LabelName`s associated with it
- Some way[*] of observing a metrics together with labels
   - Easiest way is for `record :: Map LabelName Text -> observation -> Maybe (m ())`, where the `Maybe` is if the caller provides labels that aren't valid
   - Next easiest way is to copy the structure used by [prometheus-client](https://hackage.haskell.org/package/prometheus-client-0.1.0.1/docs/Prometheus.html#g:8) — a typeclass with different instances for different tuples
   - Hardest way is to have some kind of typeclass that maps arbitrary user objects to a set of labels (either a `Map LabelName Text` or something that doesn't allow for label names that aren't already associated with the vector). I don't really know how to do this, and suspect that we could add it later.
 
Does this make sense? I don't have much bandwidth in the near future but will definitely try to make some time.

**Comment by LukeHoersten** [comment]
This sounds good but I haven't looked at the code in a bit so I'm not sure if we'll run into any pitfalls with this approach. Let me review the code with this in mind.

**Comment by lukehoersten** [comment]
I know it's been quite a while but I've finally taken a look at these suggested changes. The issue is that the metric name + the labels are what make up the time series key. Adding a new label means creating a new time series and adding a new time series must take place in the RegistryT monad.

A key design element of this prometheus library is that it doesn't require you to have all metric tracking in any special monad context beyond IO. You only need to thread the RegistryT monad through if you want to register new time series at the call site (which is what you're trying to do).

So, the correct usage for your use case would be to thread the RegistryT monad transformer in your transformer stack.
