### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by erikd** [bitnomial/prometheus#48]
Current `HEAD` has more relaxed upper version bounds on `bytestring`, `containers` and `transformers`

If that can be fixed with a Hackage metadata revision then that would also be fine.

In my `cabal.project` file I currently have;
```
allow-newer:
  , prometheus:text

if impl(ghc >= 9.6)
  allow-newer:
    , prometheus:bytestring
    , prometheus:containers
    , prometheus:transformers
```

**Comment by wraithm** [comment]
Correct me if I'm wrong, but it looks like our current bounds on `containers` and `transformers` are:

```
               , containers      >= 0.5  && < 0.7
               , transformers    >= 0.4  && < 0.7
```

but the current latest packages on hackage are:

```
transformers-0.6.1.0
containers-0.6.7
```

which should fit within our bounds.

Bytestring does have a newer 0.12.0.0, but I couldn't get our package to build with the latest bytestring because a bunch of other dependencies (`scientific`, `hashable`, `random`, etc etc) have `< 0.12` as a constraint.

I was able to get this package to build with ghc 9.6.2, but it required bytestring < 0.12.

Would you mind explaining further what constraint updates you'd like to see?

**Comment by wraithm** [comment]
Btw, I did release a new version to hackage:

https://hackage.haskell.org/package/prometheus-2.2.4

**Comment by erikd** [comment]
New Hackage version is what I needed.

Thanks for a quick response.
